name: medical_fenlei
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - pillow
  - matplotlib
  - openpyxl
  - pydicom
  - pip:
      - monai
      - einops
      - pylibjpeg
      - pylibjpeg-libjpeg
      - platformdirs
      - transformers
      - sentencepiece
      - wandb
      - rich
      - typer
